// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace IvanovItog.App.Properties
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    public sealed class Resources
    {
        private static ResourceManager? resourceMan;

        private static CultureInfo? resourceCulture;

        private Resources()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    var temp = new ResourceManager("IvanovItog.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Analytics_Title => ResourceManager.GetString("Analytics_Title", resourceCulture) ?? string.Empty;

        public static string Login_Title => ResourceManager.GetString("Login_Title", resourceCulture) ?? string.Empty;

        public static string Rating_Title => ResourceManager.GetString("Rating_Title", resourceCulture) ?? string.Empty;

        public static string RequestEditor_Title => ResourceManager.GetString("RequestEditor_Title", resourceCulture) ?? string.Empty;

        public static string Requests_Title => ResourceManager.GetString("Requests_Title", resourceCulture) ?? string.Empty;

        public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture) ?? string.Empty;
    }
}
